title: Notebook
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. 
  You can edit this line in _config.yml. 
  It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: "/notebook" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll


# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache

# Set a path/url to a logo that will be displayed instead of the title
logo: https://cdn.thewirecutter.com/wp-content/media/2020/11/notebooks-2048px-2000.jpg?auto=webp&quality=75&width=980&dpr=2
# logo: /assets/logo/logo-arpit04tripathi.jpeg
# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: https://cdn.thewirecutter.com/wp-content/media/2020/11/notebooks-2048px-1996.jpg?auto=webp&quality=75&width=980&dpr=2
cdn: https://raw.githubusercontent.com/arpit04tripathi/cdn/main/notebook

# color_scheme: dark # supports "light" (default) and "dark"

# Version of mermaid library - Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
mermaid:
  version: "11.9.0"


# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
# Aux links for the upper right navigation
aux_links:
  "Udemy":
    - "https://www.udemy.com"
  "levels.fyi":
    - "https://www.levels.fyi/en-gb/t/software-engineer/locations/united-kingdom"


# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true
# External navigation links
nav_external_links:
  - title: All Roadmaps
    url: https://roadmap.sh/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Baeldung
    url: https://www.baeldung.com/spring-tutorial
    hide_icon: false
    opens_in_new_tab: true


# Exclude from processing: The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or their entries' file path in the `include:` list.
#
# ignore files for creating _site
exclude:
  - scripts/
  - docker/
  - README.md
  - .sass-cache/
  - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
  - Gemfile.lock
  - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

callouts:
  warning:
    title: Warning
    color: red
  arpit:
    title: Custom Callout
    color: pink
    opacity: 0.3

# Define the collections
# example: collection with name "src" reside in the "_src" directory
collections:
  jtd_docs:
    output: true
  src: 
    output: true
  posts:
    output: true
# Define which collections are used in just-the-docs
just_the_docs:
  collections:
    jtd_docs:
      name: JTD Docs
      nav_exclude: false
      nav_fold: true
    src: 
      name: Source Code  
      nav_exclude: true
      nav_fold: true
    posts: 
      name: Posts 
      nav_exclude: false
      nav_fold: true
