title: Notebook
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/notebook" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Set a path/url to a logo that will be displayed instead of the title
logo: https://cdn.thewirecutter.com/wp-content/media/2020/11/notebooks-2048px-2000.jpg?auto=webp&quality=75&width=980&dpr=2
# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: https://cdn.thewirecutter.com/wp-content/media/2020/11/notebooks-2048px-1996.jpg?auto=webp&quality=75&width=980&dpr=2
# Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/just-the-docs/just-the-docs"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true
# Version of mermaid library - Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
mermaid:
  version: "11.9.0"



# Build settings
# theme: minima
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# ignore files for creating _site
exclude:
  - scripts/
  - docker/
  - README.md
  - .sass-cache/
  - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
  - Gemfile.lock
  - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
